apiVersion: apps/v1
kind: Deployment
metadata:
  name: secap-inventory
  namespace: secap-compass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secap-inventory
  template:
    metadata:
      labels:
        app: secap-inventory
    spec:
      containers:
        - name: secap-inventory
          image: secap-inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
              name: http
              protocol: TCP
          env:
            - name: DB_PASSWORD
              value: admin
            - name: DB_USERNAME
              value: admin
            - name: DB_URL
              value: jdbc:postgresql://inv-postgresql.persistence:5432/postgres
            - name: ESDB_CONN
              value: "esdb+discover://eventstore-db.persistence:2113?tls=false&keepAliveTimeout=10000&keepAliveInterval=10000"
---
apiVersion: v1
kind: Service
metadata:
  name: secap-inventory
  namespace: secap-compass
spec:
  selector:
    app: secap-inventory
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP

