apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inv-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---

apiVersion: v1
kind: Service
metadata:
  name: inv-postgresql
spec:
  selector:
    app: inv-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inv-postgresql
spec:
  serviceName: inv-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: inv-postgresql
  template:
    metadata:
      labels:
        app: inv-postgresql
    spec:
      containers:
        - name: inv-postgresql
          image: postgres:alpine
          env:
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
              name: inv-postgresql
          volumeMounts:
            - name: inv-postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: inv-postgresql
          persistentVolumeClaim:
            claimName: inv-postgresql
