spring:
  application.name: secap-inventory-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

eventstoredb:
  connectionString: "esdb://localhost:2113?tls=false"
  consumer-groups:
    building-created-consumer-group: building.created.consumer.group
    building-measured-consumer-group: building.measured.consumer.group

server:
  port: 8003
